import { useState } from 'react'
import { X, MapPin, Sun, Mountain, Zap, Leaf, ExternalLink, Download, Share2, FileText } from 'lucide-react'
import { jsPDF } from 'jspdf'
import 'jspdf-autotable'

export default function SiteDetailModal({ site, onClose }) {
  const [showFullReport, setShowFullReport] = useState(false)
  const [shareMessage, setShareMessage] = useState('')

  const getProgressBarColor = (score) => {
    if (score >= 90) return 'bg-green-500'
    if (score >= 75) return 'bg-yellow-500'
    if (score >= 60) return 'bg-orange-500'
    return 'bg-red-500'
  }

  // Satellite View - Opens Google Maps satellite view
  const handleSatelliteView = () => {
    const lat = site.coordinates.lat
    const lon = site.coordinates.lon
    const url = `https://www.google.com/maps/@${lat},${lon},17z/data=!3m1!1e3`
    window.open(url, '_blank')
  }

  // Export PDF
  const handleExportPDF = () => {
    const doc = new jsPDF()

    // Title
    doc.setFontSize(20)
    doc.setTextColor(234, 88, 12) // Orange
    doc.text('SolarScope Site Report', 20, 20)

    // Site Info
    doc.setFontSize(16)
    doc.setTextColor(0, 0, 0)
    doc.text(`Site #${site.rank}`, 20, 35)

    doc.setFontSize(12)
    doc.text(`Overall Score: ${site.score}/100`, 20, 45)

    if (site.location_name) {
      doc.text(`Location: ${site.location_name}`, 20, 55)
      doc.text(`Type: ${site.location_type}`, 20, 62)
    }

    doc.text(`Coordinates: ${site.coordinates.lat.toFixed(4)}°N, ${Math.abs(site.coordinates.lon).toFixed(4)}°W`, 20, 72)

    // Metrics Table
    doc.autoTable({
      startY: 85,
      head: [['Metric', 'Value', 'Score']],
      body: [
        ['Solar Irradiance', `${site.metrics.solar_irradiance} kWh/m²/day`, `${site.metrics.solar_irradiance_score}/100`],
        ['Terrain Slope', `${site.metrics.slope}°`, `${site.metrics.slope_score}/100`],
        ['Grid Distance', `${site.metrics.grid_distance} km`, `${site.metrics.grid_distance_score}/100`],
        ['Land Cover', site.metrics.land_cover, `${site.metrics.land_cover_score}/100`]
      ],
      theme: 'grid',
      headStyles: { fillColor: [234, 88, 12] }
    })

    // AI Analysis
    if (site.explanation) {
      const finalY = doc.lastAutoTable.finalY + 15
      doc.setFontSize(14)
      doc.text('AI Analysis', 20, finalY)

      doc.setFontSize(10)
      const splitText = doc.splitTextToSize(site.explanation, 170)
      doc.text(splitText, 20, finalY + 10)
    }

    // Footer
    const pageHeight = doc.internal.pageSize.height
    doc.setFontSize(8)
    doc.setTextColor(128, 128, 128)
    doc.text('Generated by SolarScope - AI-Powered Site Discovery', 20, pageHeight - 10)
    doc.text(new Date().toLocaleDateString(), 170, pageHeight - 10)

    // Save
    doc.save(`SolarScope_Site_${site.rank}_Report.pdf`)
  }

  // Share Site
  const handleShare = async () => {
    const shareUrl = `${window.location.origin}?site=${site.coordinates.lat},${site.coordinates.lon}&rank=${site.rank}`
    const shareText = `Check out this solar site #${site.rank} (Score: ${site.score}/100) ${site.location_name ? `in ${site.location_name}` : ''} - ${shareUrl}`

    try {
      if (navigator.share) {
        await navigator.share({
          title: `SolarScope Site #${site.rank}`,
          text: shareText,
          url: shareUrl
        })
      } else {
        // Fallback: Copy to clipboard
        await navigator.clipboard.writeText(shareText)
        setShareMessage('✓ Link copied to clipboard!')
        setTimeout(() => setShareMessage(''), 3000)
      }
    } catch (error) {
      // Fallback: Copy to clipboard
      try {
        await navigator.clipboard.writeText(shareText)
        setShareMessage('✓ Link copied to clipboard!')
        setTimeout(() => setShareMessage(''), 3000)
      } catch (err) {
        setShareMessage('✗ Failed to copy link')
        setTimeout(() => setShareMessage(''), 3000)
      }
    }
  }

  // Full Report View
  const handleFullReport = () => {
    setShowFullReport(!showFullReport)
  }

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4" style={{ zIndex: 9999 }}>
      <div className="bg-white rounded-lg shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto relative" style={{ zIndex: 10000 }}>
        {/* Header */}
        <div className="bg-gradient-to-r from-solar-orange to-solar-gold text-white px-6 py-4 flex items-center justify-between sticky top-0 z-10">
          <div>
            <h2 className="text-2xl font-bold">Site #{site.rank}</h2>
            <div className="text-sm opacity-90">Overall Score: {site.score}/100</div>
          </div>
          <button
            onClick={onClose}
            className="hover:bg-white/20 rounded-full p-2 transition"
          >
            <X size={24} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6">
          {/* Location */}
          <div className="space-y-2">
            {site.location_name && (
              <div className="flex items-start text-gray-700">
                <MapPin className="mr-2 text-solar-orange mt-0.5" size={20} />
                <div>
                  <span className="font-semibold block">{site.location_name}</span>
                  <span className="text-sm text-gray-600 italic">{site.location_type}</span>
                </div>
              </div>
            )}
            <div className="flex items-center text-gray-600 text-sm ml-7">
              📍 {site.coordinates.lat.toFixed(4)}°N, {Math.abs(site.coordinates.lon).toFixed(4)}°W
            </div>
          </div>

          {/* Detailed Scoring */}
          <div>
            <h3 className="text-lg font-bold text-gray-800 mb-4">📊 Detailed Scoring</h3>

            {/* Solar Irradiance */}
            <div className="mb-4">
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center">
                  <Sun className="mr-2 text-solar-orange" size={18} />
                  <span className="font-semibold text-gray-700">Solar Irradiance</span>
                </div>
                <span className="text-sm font-bold text-gray-800">
                  {site.metrics.solar_irradiance_score}/100
                </span>
              </div>
              <div className="w-full bg-gray-200 rounded-full h-3 overflow-hidden">
                <div
                  className={`h-full ${getProgressBarColor(site.metrics.solar_irradiance_score)} transition-all duration-500`}
                  style={{ width: `${site.metrics.solar_irradiance_score}%` }}
                ></div>
              </div>
              <div className="text-xs text-gray-600 mt-1">
                {site.metrics.solar_irradiance} kWh/m²/day
              </div>
            </div>

            {/* Terrain Slope */}
            <div className="mb-4">
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center">
                  <Mountain className="mr-2 text-solar-green" size={18} />
                  <span className="font-semibold text-gray-700">Terrain Slope</span>
                </div>
                <span className="text-sm font-bold text-gray-800">
                  {site.metrics.slope_score}/100
                </span>
              </div>
              <div className="w-full bg-gray-200 rounded-full h-3 overflow-hidden">
                <div
                  className={`h-full ${getProgressBarColor(site.metrics.slope_score)} transition-all duration-500`}
                  style={{ width: `${site.metrics.slope_score}%` }}
                ></div>
              </div>
              <div className="text-xs text-gray-600 mt-1">
                {site.metrics.slope}° average
              </div>
            </div>

            {/* Grid Distance */}
            <div className="mb-4">
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center">
                  <Zap className="mr-2 text-solar-blue" size={18} />
                  <span className="font-semibold text-gray-700">Grid Distance</span>
                </div>
                <span className="text-sm font-bold text-gray-800">
                  {site.metrics.grid_distance_score}/100
                </span>
              </div>
              <div className="w-full bg-gray-200 rounded-full h-3 overflow-hidden">
                <div
                  className={`h-full ${getProgressBarColor(site.metrics.grid_distance_score)} transition-all duration-500`}
                  style={{ width: `${site.metrics.grid_distance_score}%` }}
                ></div>
              </div>
              <div className="text-xs text-gray-600 mt-1">
                {site.metrics.grid_distance} km to transmission line
              </div>
            </div>

            {/* Land Cover */}
            <div className="mb-4">
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center">
                  <Leaf className="mr-2 text-green-600" size={18} />
                  <span className="font-semibold text-gray-700">Land Cover</span>
                </div>
                <span className="text-sm font-bold text-gray-800">
                  {site.metrics.land_cover_score}/100
                </span>
              </div>
              <div className="w-full bg-gray-200 rounded-full h-3 overflow-hidden">
                <div
                  className={`h-full ${getProgressBarColor(site.metrics.land_cover_score)} transition-all duration-500`}
                  style={{ width: `${site.metrics.land_cover_score}%` }}
                ></div>
              </div>
              <div className="text-xs text-gray-600 mt-1 capitalize">
                {site.metrics.land_cover}
              </div>
            </div>
          </div>

          {/* AI Analysis */}
          {site.explanation && (
            <div>
              <h3 className="text-lg font-bold text-gray-800 mb-3">🤖 AI Analysis</h3>
              <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 text-gray-700 leading-relaxed">
                {site.explanation}
              </div>
            </div>
          )}

          {/* Full Report Section */}
          {showFullReport && (
            <div className="bg-blue-50 border-2 border-blue-200 rounded-lg p-6 space-y-4">
              <h3 className="text-xl font-bold text-blue-900 mb-4">📋 Comprehensive Site Report</h3>

              {/* Site Overview */}
              <div className="bg-white rounded-lg p-4 border border-blue-300">
                <h4 className="font-semibold text-blue-800 mb-2">📍 Site Overview</h4>
                <div className="grid grid-cols-2 gap-3 text-sm text-gray-700">
                  <div>
                    <span className="font-semibold">Overall Score:</span> {site.score}/100
                  </div>
                  <div>
                    <span className="font-semibold">Ranking:</span> #{site.rank}
                  </div>
                  {site.location_name && (
                    <>
                      <div className="col-span-2">
                        <span className="font-semibold">Location:</span> {site.location_name}
                      </div>
                      <div className="col-span-2">
                        <span className="font-semibold">Type:</span> {site.location_type}
                      </div>
                    </>
                  )}
                  <div className="col-span-2">
                    <span className="font-semibold">Coordinates:</span> {site.coordinates.lat.toFixed(4)}°N, {Math.abs(site.coordinates.lon).toFixed(4)}°W
                  </div>
                </div>
              </div>

              {/* Key Strengths - Dynamic based on actual scores */}
              <div>
                <h4 className="font-semibold text-blue-800 mb-2">✨ Key Strengths</h4>
                <ul className="list-disc list-inside text-gray-700 space-y-1">
                  {site.metrics.solar_irradiance_score >= 80 && (
                    <li>
                      <strong>Excellent solar irradiance:</strong> {site.metrics.solar_irradiance} kWh/m²/day
                      ({site.metrics.solar_irradiance_score}/100 score) -
                      {site.metrics.solar_irradiance >= 6.5 ? ' Top tier for solar production' :
                       site.metrics.solar_irradiance >= 5.5 ? ' Above average for the region' :
                       ' Suitable for solar installations'}
                    </li>
                  )}
                  {site.metrics.slope_score >= 85 && (
                    <li>
                      <strong>Optimal terrain:</strong> {site.metrics.slope}° average slope
                      ({site.metrics.slope_score}/100 score) -
                      {site.metrics.slope <= 2 ? ' Virtually flat, minimal grading needed' :
                       site.metrics.slope <= 5 ? ' Very gentle slope, ideal for panels' :
                       ' Acceptable grade for installation'}
                    </li>
                  )}
                  {site.metrics.grid_distance_score >= 75 && (
                    <li>
                      <strong>Grid proximity:</strong> {site.metrics.grid_distance} km to transmission infrastructure
                      ({site.metrics.grid_distance_score}/100 score) -
                      {site.metrics.grid_distance <= 5 ? ' Excellent access, low connection costs' :
                       site.metrics.grid_distance <= 15 ? ' Good proximity to grid' :
                       ' Moderate distance to grid'}
                    </li>
                  )}
                  {site.metrics.land_cover_score >= 75 && (
                    <li>
                      <strong>Suitable land cover:</strong> {site.metrics.land_cover}
                      ({site.metrics.land_cover_score}/100 score) -
                      {site.metrics.land_cover === 'barren' ? ' Minimal clearing required' :
                       site.metrics.land_cover === 'grassland' ? ' Easy to develop' :
                       site.metrics.land_cover === 'cropland' ? ' Agricultural conversion possible' :
                       ' Development feasible'}
                    </li>
                  )}
                  {/* Show at least one strength even for lower-scoring sites */}
                  {site.metrics.solar_irradiance_score < 80 &&
                   site.metrics.slope_score < 85 &&
                   site.metrics.grid_distance_score < 75 &&
                   site.metrics.land_cover_score < 75 && (
                    <li>
                      <strong>Balanced performance:</strong> Overall score of {site.score}/100 indicates viable development potential with proper planning
                    </li>
                  )}
                </ul>
              </div>

              {/* Detailed Metrics Breakdown */}
              <div className="bg-white rounded-lg p-4 border border-blue-300">
                <h4 className="font-semibold text-blue-800 mb-3">📊 Detailed Metrics Analysis</h4>
                <div className="space-y-2 text-sm text-gray-700">
                  <div className="flex justify-between">
                    <span><strong>Solar Irradiance:</strong> {site.metrics.solar_irradiance} kWh/m²/day</span>
                    <span className={`font-semibold ${site.metrics.solar_irradiance_score >= 80 ? 'text-green-600' : site.metrics.solar_irradiance_score >= 60 ? 'text-yellow-600' : 'text-orange-600'}`}>
                      {site.metrics.solar_irradiance_score >= 80 ? 'Excellent' : site.metrics.solar_irradiance_score >= 60 ? 'Good' : 'Moderate'}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span><strong>Terrain Slope:</strong> {site.metrics.slope}° average</span>
                    <span className={`font-semibold ${site.metrics.slope_score >= 85 ? 'text-green-600' : site.metrics.slope_score >= 70 ? 'text-yellow-600' : 'text-orange-600'}`}>
                      {site.metrics.slope <= 3 ? 'Flat' : site.metrics.slope <= 7 ? 'Gentle' : 'Moderate'}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span><strong>Grid Distance:</strong> {site.metrics.grid_distance} km</span>
                    <span className={`font-semibold ${site.metrics.grid_distance_score >= 75 ? 'text-green-600' : site.metrics.grid_distance_score >= 50 ? 'text-yellow-600' : 'text-orange-600'}`}>
                      {site.metrics.grid_distance <= 10 ? 'Near' : site.metrics.grid_distance <= 20 ? 'Moderate' : 'Far'}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span><strong>Land Cover:</strong> {site.metrics.land_cover}</span>
                    <span className={`font-semibold ${site.metrics.land_cover_score >= 75 ? 'text-green-600' : site.metrics.land_cover_score >= 50 ? 'text-yellow-600' : 'text-orange-600'}`}>
                      {site.metrics.land_cover_score >= 75 ? 'Ideal' : site.metrics.land_cover_score >= 50 ? 'Suitable' : 'Fair'}
                    </span>
                  </div>
                </div>
              </div>

              {/* Considerations - Dynamic based on actual metrics */}
              <div>
                <h4 className="font-semibold text-blue-800 mb-2">⚠️ Development Considerations</h4>
                <ul className="list-disc list-inside text-gray-700 space-y-1">
                  {site.metrics.grid_distance > 15 && (
                    <li>
                      <strong>Grid connection:</strong> Distance of {site.metrics.grid_distance} km may require significant transmission infrastructure investment
                      (estimated ${Math.round(site.metrics.grid_distance * 50000).toLocaleString()}-${Math.round(site.metrics.grid_distance * 100000).toLocaleString()})
                    </li>
                  )}
                  {site.metrics.slope > 5 && (
                    <li>
                      <strong>Terrain preparation:</strong> {site.metrics.slope}° slope requires grading and leveling
                      (estimated ${Math.round(50 * 4000 * (site.metrics.slope / 10)).toLocaleString()} for 50-acre site)
                    </li>
                  )}
                  {site.metrics.solar_irradiance < 5 && (
                    <li>
                      <strong>Solar efficiency:</strong> Irradiance of {site.metrics.solar_irradiance} kWh/m²/day is below optimal,
                      expect {Math.round((1 - site.metrics.solar_irradiance/6.5) * 100)}% lower energy production vs. ideal sites
                    </li>
                  )}
                  {site.metrics.land_cover_score < 60 && (
                    <li>
                      <strong>Land preparation:</strong> {site.metrics.land_cover} may require clearing or remediation before development
                    </li>
                  )}
                  {/* Always include permitting */}
                  <li>
                    <strong>Regulatory compliance:</strong> Standard environmental assessments, zoning approvals, and utility interconnection agreements required
                  </li>
                </ul>
              </div>

              {/* Estimated Capacity - Dynamic calculations */}
              <div className="bg-white rounded-lg p-4 border border-blue-300">
                <h4 className="font-semibold text-blue-800 mb-2">⚡ Energy Production Estimates</h4>
                <div className="space-y-3 text-sm text-gray-700">
                  {/* 50-acre installation */}
                  <div>
                    <p className="font-semibold text-gray-800 mb-1">50-Acre Installation:</p>
                    <ul className="list-disc list-inside ml-2 space-y-1">
                      <li>
                        Daily generation: <strong>{(site.metrics.solar_irradiance * 50 * 0.15).toFixed(1)} MWh/day</strong>
                      </li>
                      <li>
                        Annual generation: <strong>{(site.metrics.solar_irradiance * 50 * 0.15 * 365).toFixed(0)} MWh/year</strong>
                      </li>
                      <li>
                        Homes powered: <strong>{Math.round(site.metrics.solar_irradiance * 50 * 0.15 * 30 / 0.9)}</strong> per month
                        (based on 900 kWh/month average)
                      </li>
                      <li>
                        Estimated capacity: <strong>{(site.metrics.solar_irradiance * 50 * 0.2).toFixed(1)} MW</strong> DC installed
                      </li>
                    </ul>
                  </div>

                  {/* 100-acre installation */}
                  <div>
                    <p className="font-semibold text-gray-800 mb-1">100-Acre Installation:</p>
                    <ul className="list-disc list-inside ml-2 space-y-1">
                      <li>
                        Daily generation: <strong>{(site.metrics.solar_irradiance * 100 * 0.15).toFixed(1)} MWh/day</strong>
                      </li>
                      <li>
                        Annual generation: <strong>{(site.metrics.solar_irradiance * 100 * 0.15 * 365).toFixed(0)} MWh/year</strong>
                      </li>
                      <li>
                        Homes powered: <strong>{Math.round(site.metrics.solar_irradiance * 100 * 0.15 * 30 / 0.9)}</strong> per month
                      </li>
                      <li>
                        Estimated capacity: <strong>{(site.metrics.solar_irradiance * 100 * 0.2).toFixed(1)} MW</strong> DC installed
                      </li>
                    </ul>
                  </div>

                  {/* Carbon offset */}
                  <div className="pt-2 border-t border-blue-200">
                    <p className="font-semibold text-green-700">
                      🌱 Environmental Impact (50-acre):
                    </p>
                    <p className="ml-2">
                      Estimated <strong>{Math.round(site.metrics.solar_irradiance * 50 * 0.15 * 365 * 0.5)}</strong> tons of CO₂
                      offset annually (equivalent to planting <strong>{Math.round(site.metrics.solar_irradiance * 50 * 0.15 * 365 * 0.5 * 40)}</strong> trees)
                    </p>
                  </div>
                </div>
              </div>

              {/* Next Steps - Prioritized based on site weaknesses */}
              <div>
                <h4 className="font-semibold text-blue-800 mb-2">🚀 Recommended Action Plan</h4>
                <ol className="list-decimal list-inside text-gray-700 space-y-1">
                  <li>
                    <strong>Site survey:</strong> Conduct geotechnical assessment
                    {site.metrics.slope > 5 && ' with focus on grading requirements'}
                  </li>
                  <li>
                    <strong>Title & zoning:</strong> Verify land ownership, easements, and local zoning compliance for renewable energy development
                  </li>
                  <li>
                    <strong>Utility coordination:</strong> Contact local utility for interconnection application
                    {site.metrics.grid_distance > 15 && ' and transmission upgrade feasibility study'}
                  </li>
                  <li>
                    <strong>Environmental review:</strong> Complete NEPA or state environmental assessment
                    {site.metrics.land_cover_score < 60 && ' including habitat surveys'}
                  </li>
                  <li>
                    <strong>Financial modeling:</strong> Develop pro forma with actual metrics -
                    estimated project cost ${Math.round((site.metrics.solar_irradiance * 50 * 0.2 * 1000000) + (site.metrics.grid_distance * 75000)).toLocaleString()}-
                    ${Math.round((site.metrics.solar_irradiance * 50 * 0.2 * 1500000) + (site.metrics.grid_distance * 125000)).toLocaleString()}
                    for 50-acre installation
                  </li>
                  <li>
                    <strong>Permits & approvals:</strong> Secure building permits, special use permits, and utility interconnection agreement
                  </li>
                </ol>
              </div>
            </div>
          )}

          {/* Share Message */}
          {shareMessage && (
            <div className={`text-center py-2 px-4 rounded-lg ${shareMessage.includes('✓') ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
              {shareMessage}
            </div>
          )}

          {/* Action Buttons */}
          <div className="grid grid-cols-2 gap-3 pt-4 border-t">
            <button
              onClick={handleSatelliteView}
              className="flex items-center justify-center gap-2 px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg transition font-semibold"
            >
              <ExternalLink size={18} />
              Satellite View
            </button>
            <button
              onClick={handleExportPDF}
              className="flex items-center justify-center gap-2 px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg transition font-semibold"
            >
              <Download size={18} />
              Export PDF
            </button>
            <button
              onClick={handleShare}
              className="flex items-center justify-center gap-2 px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg transition font-semibold"
            >
              <Share2 size={18} />
              Share Site
            </button>
            <button
              onClick={handleFullReport}
              className={`flex items-center justify-center gap-2 px-4 py-2 rounded-lg transition font-semibold ${
                showFullReport
                  ? 'bg-blue-600 text-white hover:bg-blue-700'
                  : 'bg-gradient-to-r from-solar-orange to-solar-gold text-white hover:shadow-lg'
              }`}
            >
              <FileText size={18} />
              {showFullReport ? 'Hide Report' : 'Full Report'}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
